name = "MultivariateExpansions"
uuid = "9d32bc2f-1c07-4c0c-b0b2-5edd4e076357"
authors = ["Daniel Sharp <dannys4@mit.edu> and contributors"]
version = "1.0.6"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
MultiIndexing = "b97ecbdf-1535-430e-a7c7-b5702749f368"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
MuladdMacro = "0.2"
MultiIndexing = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
